application: theitalianbay
version: 1
runtime: python
api_version: 1

handlers:
- url: /static
  static_dir: static
- url: /favicon\.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico
  mime_type: image/vnd.microsoft.icon
- url: /robots\.txt
  static_files: static/robots.txt
  upload: static/robots.txt
- url: .*
  script: handlers/main.py
